FROM palfrey/rustup-watchexec:1.26 as watchexec

FROM golang:1.13.0-stretch AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=1

WORKDIR /app

# Dependecies
COPY go.mod .
COPY go.sum .
RUN go mod download

# Watcher
COPY --from=watchexec /root/.cargo/bin/watchexec /bin/

# Source
COPY . ./
